apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-web-api-deployment
spec:
  replicas: 3  # Set the number of replicas as needed
  selector:
    matchLabels:
      app: cqrs-web-api
  template:
    metadata:
      labels:
        app: cqrs-web-api
    spec:
      containers:
        - name: cqrs-web-api
          image: your-docker-image:tag  # Replace with your Docker image and tag
          ports:
            - containerPort: 8080  # Match the port your application listens on
